-- Populate tables

INSERT INTO DMT.WORKING_COPY (
	ID, 
	NAME,
	DESCRIPTION,
	DESIGN_MODE, 
	MODEL_DEFINITION, 
	CREATED, 	 
	LAST_MODIFIED, 	 
	VERSION 
) SELECT RANDOM_UUID(),
		'LITP deployment model',
		'Real deployment model managed by a LITP server',
		'LIVE',
		NULL,
		CURRENT_TIMESTAMP(),
		CURRENT_TIMESTAMP(),
		0
WHERE NOT EXISTS (SELECT 1 FROM  DMT.WORKING_COPY WHERE DESIGN_MODE = 'LIVE')